<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="XecronixCursor">
      <HintPath>..\..\..\XecronixCursor\src\XecronixCursor\bin\Debug\net10.0\XecronixCursor.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>